version: '3.8'

services:

  web:
    build:
      context: .
    container_name: gus_service
    volumes:
      - .:/app/
    restart: always
    ports:
      - 8000:8000
    command: python -m api
    environment:
      - PYTHONPATH=/app/
      - CONFIG_PATH=/app/configs/config-test.yaml
